export const queries = {
  reportFights:
    "query GetReportFights($reportCode: String!) {\n          reportData {\n            report(code: $reportCode, allowUnlisted: true) {\n              startTime\n              fights(translate: true) {\n                id\n                name\n                encounterID\n                difficulty\n                kill\n                keystoneLevel\n                keystoneTime\n                startTime\n                endTime\n              }\n            }\n          }\n        }",
  fightSegments:
    "query GetFightSegments($reportCode: String!, $fightId: Int!) {\n          reportData {\n            report(code: $reportCode, allowUnlisted: true) {\n              startTime\n              phases {\n                encounterID\n                phases {\n                  id\n                  name\n                  isIntermission\n                }\n              }\n              fights(fightIDs: [$fightId], translate: true) {\n                id\n                name\n                encounterID\n                difficulty\n                kill\n                startTime\n                endTime\n                dungeonPulls {\n                  id\n                  name\n                  encounterID\n                  kill\n                  startTime\n                  endTime\n                }\n                phaseTransitions {\n                  id\n                  startTime\n                }\n              }\n            }\n          }\n        }",
  fightContext:
    "query GetFightContext($reportCode: String!, $fightId: Int!) {\n          reportData {\n            report(code: $reportCode, allowUnlisted: true) {\n              startTime\n              fights(fightIDs: [$fightId], translate: true) {\n                id\n                startTime\n                endTime\n                friendlyPlayers\n                enemyPlayers\n                friendlyNPCs { id instanceCount petOwner }\n                friendlyPets { id instanceCount petOwner }\n                enemyNPCs { id instanceCount petOwner }\n                enemyPets { id instanceCount petOwner }\n              }\n              masterData(translate: true) {\n                actors {\n                  id\n                  name\n                  type\n                  subType\n                  petOwner\n                }\n                abilities {\n                  gameID\n                  name\n                  icon\n                  type\n                }\n              }\n            }\n          }\n        }",
  fightAbilityEvents:
    "query GetFightAbilityEvents(\n          $reportCode: String!\n          $fightId: Int!\n          $startTime: Float!\n          $endTime: Float!\n          $hostilityType: HostilityType!\n          $dataType: EventDataType!\n          $viewOptions: Int\n        ) {\n          reportData {\n            report(code: $reportCode, allowUnlisted: true) {\n              events(\n                dataType: $dataType\n                fightIDs: [$fightId]\n                startTime: $startTime\n                endTime: $endTime\n                hostilityType: $hostilityType\n                limit: 10000\n                translate: true\n                viewOptions: $viewOptions\n              ) {\n                data\n                nextPageTimestamp\n              }\n            }\n          }\n        }",
} as const;
